services:
  - type: web
    name: cas-download-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 300
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.11.0
